### PR TITLE
Un-break building under arm64

### PR DESCRIPTION
**Pull request by rshura**
The -msse option is specific to x86_64, it does not build under arm64.

### CODE REVIEW

**Comment by Dobatymo** [comment]
It would be better to check if the architecture is ARM64, otherwise the binaries which are built for linux on pypi are too specific to the github actions system. Maybe using `platform.machine() == "aarch64"`.

**Comment by rshura** [comment]
I don't quite understand the objection. If the build is happening on x86_64 then `-march=native` will include all `-msse` flags that are appropriate for the hardware. If the build is happening on any other hardware architecture than x86_64, not just arm64, but anything else, then `-msse4.2` will fail.  I happened to trigger this on arm64, but it would be the same for anything else.

There's of course a question of what if github builds on arch X and I want to use arch Y, but that is a different issue altogether.

**Comment by Dobatymo** [comment]
Because the wheels are built with github actions arch=native will optimize for the github runner cpus. They should work on other CPUs also because the pypi wheels are mostly for the convenience of people who cannot build the wheels by themselves. sse4.2 is important for good performance on x86 64 so I included that flag.

So perhaps the ss3 flag should be behind a `platform.machine().lower() in ("x86_64", "amd64")` (or similar) guard instead.

**Comment by rshura** [comment]
I did as you suggested.

**Comment by Dobatymo** [comment]
Hi, could you add `import platform` on top please?

**Comment by Dobatymo** [comment]
Thanks!

**Pull request merged**
